import { computed, Injectable, signal } from '@angular/core';
import { Nutrition, Product, ProductQuantities } from './product.model';

export const EMPTY_NUTRITION: Nutrition = Object.freeze({
  calories: 0,
  carbs: 0,
  sugar: 0,
  fiber: 0,
  fat: 0,
  protein: 0,
  sodium: 0,
  caffeine: 0,
  salt: 0,
  potassium: 0,
  magnesium: 0,
  calcium: 0,
});

const PRODUCTS: ReadonlyArray<Product> = Object.freeze([
  {
    id: 'maurten-gel-100-caf-100',
    brand: 'Maurten',
    name: 'Gel 100 Caf 100',
    type: 'race',
    kind: 'gel',
    serving: '1 sachet, 40 g',
    servingGrams: 40,
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/us/gel-100-caf-100-box-us',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 100,
      carbs: 25,
      sugar: 25,
      salt: 0.055,
      sodium: 22,
      caffeine: 100,
    },
  },
  {
    id: 'maurten-gel-160',
    brand: 'Maurten',
    name: 'Gel 160',
    type: 'race',
    kind: 'gel',
    serving: '1 sachet, 65 g',
    servingGrams: 65,
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/gb/gel-160',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 160,
      carbs: 40,
      sugar: 40,
      salt: 0.08,
      sodium: 32,
    },
  },
  {
    id: 'maurten-drink-mix-320-caf-100',
    brand: 'Maurten',
    name: 'Drink Mix 320 Caf 100',
    type: 'race',
    kind: 'drink',
    serving: '1 sachet in 500 ml, 83 g',
    servingGrams: 83,
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/us/drink-mix-320-caf-100-us',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 320,
      carbs: 80,
      sugar: 37,
      salt: 0.63,
      sodium: 250,
      caffeine: 100,
    },
  },
  {
    id: 'maurten-solid-160',
    brand: 'Maurten',
    name: 'Solid 160',
    type: 'race',
    kind: 'solid',
    serving: '1 bar, 55 g',
    servingGrams: 55,
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/mt/solid-160',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 199,
      carbs: 40,
      sugar: 17.5,
      fiber: 1.4,
      fat: 3.1,
      protein: 2.2,
      salt: 0.62,
      sodium: 244,
    },
  },
  {
    id: 'maurten-solid-c-160',
    brand: 'Maurten',
    name: 'Solid C 160',
    type: 'race',
    kind: 'solid',
    serving: '1 bar, 55 g',
    servingGrams: 55,
    sourceLabel: 'Maurten',
    sourceUrl: 'https://www.maurten.com/products/cz/solid-c-160',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 204,
      carbs: 40,
      sugar: 19.4,
      fiber: 2.2,
      fat: 3.2,
      protein: 2.6,
      salt: 0.62,
      sodium: 244,
    },
  },
  {
    id: 'baouw-puree-raspberry-strawberry-basil',
    brand: 'Baouw',
    name: 'Energy Purée Raspberry Strawberry Basil',
    type: 'race',
    kind: 'puree',
    serving: '1 purée, 90 g',
    servingGrams: 90,
    sourceLabel: 'Baouw',
    sourceUrl:
      'https://www.baouw-organic-nutrition.com/en_GB/shop/energy-puree-bio-raspberry-strawberry-basil-891',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 62,
      carbs: 11,
      sugar: 9.3,
      fiber: 0.3,
      fat: 1.8,
      protein: 0.3,
      salt: 0.03,
      sodium: 1,
      potassium: 150,
      magnesium: 18,
      calcium: 36,
    },
  },
  {
    id: 'baouw-electrolytes-blackberry',
    brand: 'Baouw',
    name: 'Electrolytes Blackberry Blackcurrant',
    type: 'race',
    kind: 'electrolyte',
    serving: '1 tablet in 500 ml, 5 g',
    servingGrams: 5,
    sourceLabel: 'Baouw',
    sourceUrl:
      'https://www.baouw-organic-nutrition.com/en_GB/shop/electrolyte-blackberry-blackcurrant-1238',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 11,
      carbs: 1.5,
      sugar: 0.03,
      fiber: 0.019,
      protein: 0.006,
      salt: 0.759,
      sodium: 300,
      potassium: 300,
      magnesium: 56.25,
      calcium: 50,
    },
  },
  {
    id: 'decathlon-fruit-jellies-citrus',
    brand: 'Decathlon',
    name: 'Energy Fruit Jellies Citrus',
    type: 'race',
    kind: 'jelly',
    serving: '1 bar, 25 g',
    servingGrams: 25,
    sourceLabel: 'Decathlon',
    sourceUrl:
      'https://www.decathlon.co.uk/p/energy-fruit-jelly-ecosize-12x25g-citrus/311136/g4m8562277',
    nutritionPerServing: {
      ...EMPTY_NUTRITION,
      calories: 84,
      carbs: 21,
      sugar: 16,
      fat: 0.5,
      protein: 0.5,
      salt: 0.06,
      sodium: 24,
    },
  },
  {
    id: 'rolled-oats',
    name: 'Rolled oats',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical dry portion: 40-80 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 389,
      carbs: 66.3,
      sugar: 0.9,
      fiber: 10.6,
      fat: 6.9,
      protein: 16.9,
    },
  },
  {
    id: 'banana',
    name: 'Banana',
    type: 'both',
    kind: 'fruit',
    serving: '1 medium peeled banana, about 120 g',
    servingGrams: 120,
    servingSuggestion: 'One medium peeled banana: about 120 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 89,
      carbs: 22.8,
      sugar: 12.2,
      fiber: 2.6,
      fat: 0.3,
      protein: 1.1,
    },
  },
  {
    id: 'plantain-banana',
    name: 'Plantain banana',
    type: 'daily',
    kind: 'fruit',
    servingSuggestion: 'One medium peeled plantain banana: about 150 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 125,
      carbs: 28.9,
      sugar: 14,
      fiber: 2.3,
      fat: 0.4,
      protein: 0.79,
      salt: 0.013,
    },
  },
  {
    id: 'melon',
    name: 'Melon',
    type: 'daily',
    kind: 'fruit',
    servingSuggestion: 'One medium melon: about 200 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 59.8,
      carbs: 14.8,
      sugar: 10.6,
      fiber: 1.3,
      fat: 0.5,
      protein: 1.13,
      salt: 0.013,
    },
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    type: 'daily',
    kind: 'fruit',
    servingSuggestion: 'One medium watermelon: about 300 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 35.4,
      carbs: 8.33,
      sugar: 7.9,
      fiber: 0.5,
      fat: 0.5,
      protein: 0.69,
      salt: 0.013,
    },
  },
  {
    id: 'salad-letuce',
    name: 'Salad, lettuce',
    type: 'daily',
    kind: 'vegetable',
    servingSuggestion: 'One medium salad: about 100 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 15,
      fat: 0.6,
      carbs: 1.1,
      sugar: 1.0,
      fiber: 0.9,
      protein: 1.0,
      salt: 0.02,
    },
  },
  {
    id: 'white-rice-cooked',
    name: 'White rice, cooked',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: 150-250 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 130,
      carbs: 28.2,
      sugar: 0.1,
      fiber: 0.4,
      fat: 0.3,
      protein: 2.7,
    },
  },
  {
    id: 'pasta-cooked',
    name: 'Pasta, cooked',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: 150-250 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 361,
      carbs: 72,
      sugar: 3.7,
      fiber: 3.6,
      fat: 2,
      protein: 12,
    },
  },
  {
    id: 'gnocchi-cooked',
    name: 'Gnocchi, cooked',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: 100-150 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 150,
      fat: 0.5,
      carbs: 32,
      sugar: 0.5,
      fiber: 2.9,
      protein: 4.1,
      salt: 1.1,
    },
  },
  {
    id: 'fajitas-complete-meal',
    name: 'Fajitas, complete meal',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: Pour 58 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 293,
      carbs: 47.8,
      sugar: 2.3,
      fiber: 5.5,
      fat: 6,
      protein: 9.1,
      salt: 1.05,
    },
  },
  {
    id: 'galette-bretonne',
    name: 'Galette Bretonne',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: Pour 58 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 163,
      carbs: 31,
      sugar: 0.5,
      fiber: 3.8,
      fat: 1.6,
      protein: 5.8,
      salt: 1.3,
    },
  },
  {
    id: 'rice-flour',
    name: 'Rice flour (semi-complete)',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: Pour 58 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 355,
      carbs: 76,
      sugar: 0.3,
      fiber: 2.7,
      fat: 1.6,
      protein: 7.7,
    },
  },
  {
    id: 'coco-flour',
    name: 'Coco flour',
    type: 'daily',
    kind: 'cereal',
    servingSuggestion: 'Typical cooked portion: Pour 58 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 352,
      carbs: 27,
      sugar: 22,
      fiber: 35,
      fat: 10,
      protein: 21,
      salt: 0.1,
    },
  },
  {
    id: 'coco-sugar',
    name: 'Coco sugar',
    type: 'daily',
    kind: 'sugar',
    servingSuggestion: 'Typical serving: 1 tablespoon, about 21 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 382,
      carbs: 93,
      sugar: 86,
      fiber: 1.4,
      fat: 0.5,
      protein: 1.5,
      salt: 0.46,
    },
  },
  {
    id: 'chicken-breast-cooked',
    name: 'Chicken breast, cooked',
    type: 'daily',
    kind: 'meat',
    servingSuggestion: 'Typical cooked portion: 120-200 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 165,
      fat: 3.6,
      protein: 31,
      carbs: 0,
      sugar: 0,
      fiber: 0,
      sodium: 0,
      caffeine: 0,
      salt: 0,
      potassium: 0,
      magnesium: 0,
      calcium: 0,
    },
  },
  {
    id: 'ham',
    name: 'Ham',
    type: 'daily',
    kind: 'meat',
    servingSuggestion: 'Typical cooked portion: 120-200 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 125,
      fat: 5.0,
      protein: 19,
      carbs: 1.1,
      sugar: 1.1,
      salt: 2,
    },
  },
  {
    id: 'grated-comte',
    name: 'Grated Comte',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One portion: about 20 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 410,
      carbs: 0.5,
      sugar: 0.5,
      fat: 34,
      protein: 26,
      salt: 0.8,
    },
  },
  {
    id: 'egg-whole',
    name: 'Whole egg',
    type: 'daily',
    kind: 'meat',
    servingSuggestion: 'One medium egg without shell: about 50 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 138,
      carbs: 0.7,
      sugar: 0.4,
      fat: 9.6,
      protein: 13,
    },
  },
  {
    id: 'chocolate-dark-85',
    name: 'Chocolate, dark 85%',
    type: 'daily',
    kind: 'solid',
    servingSuggestion: 'Typical cooked portion: 20g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 588,
      carbs: 20,
      sugar: 15,
      fiber: 19,
      fat: 48,
      protein: 10,
      salt: 0.14,
    },
  },
  {
    id: 'salmon-cooked',
    name: 'Salmon, cooked',
    type: 'daily',
    kind: 'seafood',
    servingSuggestion: 'Typical cooked portion: 120-180 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 206,
      fat: 12.4,
      protein: 22.1,
    },
  },
  {
    id: 'greek-yogurt-zero-fat',
    name: 'Greek yogurt, 0% fat',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One bowl: about 150-200 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 59,
      carbs: 3.6,
      sugar: 3.2,
      fat: 0.4,
      protein: 10.3,
    },
  },
  {
    id: 'chocolate-mouse-veggie',
    name: 'Chocolate mouse veggie',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One portion: about 55 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 163,
      carbs: 19.3,
      sugar: 16.2,
      fat: 8.2,
      fiber: 1.8,
      protein: 2.2,
      salt: 0.22,
    },
  },
  {
    id: 'rice-pudding-veggie',
    name: 'Rice pudding veggie',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One portion: about 100 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 115,
      carbs: 18.7,
      sugar: 10.1,
      fat: 3.9,
      protein: 1.2,
      salt: 0.09,
    },
  },
  {
    id: 'almond-milk',
    name: 'Almond milk biorg',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One glass: about 200 ml',
    // it's 100ml, not 100g
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 29,
      carbs: 4.6,
      sugar: 3.3,
      fat: 1.2,
      protein: 0.5,
      salt: 0.06,
    },
  },
  {
    id: 'agave-syrup',
    name: 'Agave syrup',
    type: 'daily',
    kind: 'sugar',
    servingSuggestion: 'Typical serving: 1 tablespoon, about 21 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 320,
      carbs: 80,
      sugar: 79,
    },
  },
  {
    id: 'peanut-butter',
    name: 'Peanut butter',
    type: 'daily',
    kind: 'fat',
    servingSuggestion: 'Typical serving: 1 tablespoon, about 16 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 592,
      carbs: 11.5,
      sugar: 5.9,
      fat: 45.7,
      protein: 29.4,
      salt: 0.69,
    },
  },
  {
    id: 'hazelnut-butter',
    name: 'Hazelnut butter',
    type: 'daily',
    kind: 'fat',
    servingSuggestion: 'Typical serving: 1 tablespoon, about 16 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 679,
      carbs: 8.7,
      sugar: 4.4,
      fat: 62,
      protein: 17,
      salt: 0.03,
    },
  },
  {
    id: 'olive-oil',
    name: 'Olive oil',
    type: 'daily',
    kind: 'fat',
    servingSuggestion: 'One tablespoon: about 14 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 828,
      fat: 92,
    },
  },
  {
    id: 'balsamic-vinegar',
    name: 'Balsamic vinegar',
    type: 'daily',
    kind: 'sauce',
    servingSuggestion: 'One tablespoon: about 15 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 114,
      fat: 0.5,
      carbs: 28,
      sugar: 28,
      protein: 0.5,
      salt: 0.01,
    },
  },
  {
    id: 'st-moret',
    name: 'St Môret',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One portion: about 20 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 205,
      carbs: 3,
      sugar: 3,
      fat: 17.8,
      protein: 8.3,
      salt: 1.2,
    },
  },
  {
    id: 'almonds',
    name: 'Almonds',
    type: 'daily',
    kind: 'nuts',
    servingSuggestion: 'One small handful: about 30 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 579,
      carbs: 21.6,
      sugar: 4.4,
      fiber: 12.5,
      fat: 49.9,
      protein: 21.2,
    },
  },
  {
    id: 'coco-cream',
    name: 'Coco cream',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One portion: about 20 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 252,
      carbs: 4.5,
      sugar: 3,
      fiber: 0.5,
      fat: 25,
      protein: 2.7,
      salt: 0.04,
    },
  },
  {
    id: 'light-semi-thick-cream',
    name: 'Light semi-thick cream',
    type: 'daily',
    kind: 'dairy',
    servingSuggestion: 'One portion: about 20 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 188,
      carbs: 3.8,
      sugar: 3.8,
      fat: 18,
      protein: 2.7,
      salt: 0.1,
    },
  },
  {
    id: 'morilles-sauce',
    name: 'Morilles sauce',
    type: 'daily',
    kind: 'sauce',
    servingSuggestion: 'One portion: about 20 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 95.5,
      fat: 7.2,
      carbs: 5.2,
      sugar: 1.8,
      protein: 1.8,
      salt: 0.9,
    },
  },
  {
    id: 'ratatouille',
    name: 'Ratatouille Casgrain',
    type: 'daily',
    kind: 'vegetable',
    servingSuggestion: 'Typical cooked portion: 200 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 72,
      carbs: 5.7,
      sugar: 5.5,
      fiber: 3.4,
      fat: 4.1,
      protein: 1.3,
    },
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    type: 'daily',
    kind: 'vegetable',
    servingSuggestion: 'Typical cooked portion: 100-200 g',
    nutritionPer100g: {
      ...EMPTY_NUTRITION,
      calories: 34,
      carbs: 6.6,
      sugar: 1.7,
      fiber: 2.6,
      fat: 0.4,
      protein: 2.8,
    },
  },
]);

@Injectable({ providedIn: 'root' })
export class ProductService {
  private readonly catalog = signal(PRODUCTS);

  readonly allProducts = this.catalog.asReadonly();
  readonly dailyProducts = computed<ReadonlyArray<Product>>(() =>
    this.allProducts().filter((product) => product.type === 'daily' || product.type === 'both'),
  );
  readonly raceProducts = computed<ReadonlyArray<Product>>(() =>
    this.allProducts().filter((product) => product.type === 'race' || product.type === 'both'),
  );

  calculateNutritionForGrams(product: Product, grams: number): Nutrition {
    const normalizedGrams = this.normalizeAmount(grams);

    if (normalizedGrams === 0) {
      return { ...EMPTY_NUTRITION };
    }

    if (product.nutritionPer100g) {
      return this.scaleNutrition(product.nutritionPer100g, normalizedGrams / 100);
    }

    if (product.nutritionPerServing && product.servingGrams) {
      return this.scaleNutrition(
        product.nutritionPerServing,
        normalizedGrams / product.servingGrams,
      );
    }

    throw new Error(`${product.name} does not define gram-based nutrition`);
  }

  calculateNutritionForRaceServings(product: Product, servings: number): Nutrition {
    const normalizedServings = this.normalizeAmount(servings);

    if (normalizedServings === 0) {
      return { ...EMPTY_NUTRITION };
    }

    if (product.nutritionPerServing) {
      return this.scaleNutrition(product.nutritionPerServing, normalizedServings);
    }

    if (product.nutritionPer100g && product.servingGrams) {
      return this.scaleNutrition(
        product.nutritionPer100g,
        (product.servingGrams * normalizedServings) / 100,
      );
    }

    throw new Error(`${product.name} does not define race-serving nutrition`);
  }

  createEmptyQuantities(products: ReadonlyArray<Product> = this.allProducts()): ProductQuantities {
    return Object.fromEntries(products.map((product) => [product.id, 0])) as ProductQuantities;
  }

  private normalizeAmount(amount: number): number {
    return Number.isFinite(amount) ? Math.max(0, amount) : 0;
  }

  private scaleNutrition(nutrition: Nutrition, factor: number): Nutrition {
    return {
      calories: nutrition.calories * factor,
      carbs: nutrition.carbs * factor,
      sugar: nutrition.sugar * factor,
      fiber: nutrition.fiber * factor,
      fat: nutrition.fat * factor,
      protein: nutrition.protein * factor,
      sodium: nutrition.sodium * factor,
      caffeine: nutrition.caffeine * factor,
      salt: nutrition.salt * factor,
      potassium: nutrition.potassium * factor,
      magnesium: nutrition.magnesium * factor,
      calcium: nutrition.calcium * factor,
    };
  }
}
